# Polynomial Derivatives

In [ ]:
class PolyExpr:
    def __init__(self, expr, varstr="x"):
        if isinstance(expr, tuple):
            self.expr = expr
        self.varstr = varstr

    def __repr__(self):
        result = []
        for i, coeff in sorted(enumerate(self.expr), reverse=True):
            term = ""
            if coeff == 0:
                continue
            term += str(coeff)
            var = "" if i == 0 else (self.varstr if i == 1 else f"{self.varstr}^{i}")
            term += var
            result.append(term)
        return " + ".join(result)

In [ ]:
expr1 = PolyExpr((2, 4, 6))
print(expr1)
expr2 = PolyExpr((41, 212, 100), varstr="y")
print(expr2)
expr3 = PolyExpr((0, 11, 22, 33, 44, 55, 0, 77), varstr="z")
print(expr3)

6x^2 + 4x + 2
100y^2 + 212y + 41
77z^7 + 55z^5 + 44z^4 + 33z^3 + 22z^2 + 11z


In [ ]:
def polynomial_derivative(expr):
    result = []
    for i, coeff in enumerate(expr.expr):
        if i == 0:
            continue
        result.append(coeff * i)
    return PolyExpr(tuple(result), expr.varstr)

In [ ]:
expr1 = PolyExpr((2, 4, 6.5))
print(expr1)
print(polynomial_derivative(expr1), end="\n\n")

expr2 = PolyExpr((41, 6, 0, 4, 11))
print(expr2)
print(polynomial_derivative(expr2), end="\n\n")

expr3 = PolyExpr((4, -5, -72, 83))
print(expr3)
print(polynomial_derivative(expr3))
print(polynomial_derivative(polynomial_derivative(expr3)))

6.5x^2 + 4x + 2
13.0x + 4

11x^4 + 4x^3 + 6x + 41
44x^3 + 12x^2 + 6

83x^3 + -72x^2 + -5x + 4
249x^2 + -144x + -5
498x + -144


# Simple Expressions
Sum of powers, basic trig functions with powers, ln, and e^x

In [ ]:
MAX_EXPONENT = 10
OPERATIONS = ['power', 'sin', 'cos', 'ln', 'e']
NUM_OPERATIONS = len(OPERATIONS)
POWER_IDX, SIN_IDX, COS_IDX, LN_IDX, E_IDX = range(0, MAX_EXPONENT * NUM_OPERATIONS, MAX_EXPONENT)
EXPR_LIST_SIZE = MAX_EXPONENT * NUM_OPERATIONS + 1

class SimpleExpr:
    def __init__(self, expr, varstr='x'):
        if expr is not None:
            self.expr = expr.copy()
        else:
            self.expr = [0] * EXPR_LIST_SIZE
        self.varstr = varstr
    
    def __repr__(self):
        result = []
        exponent = 1
        operation_idx = 0
        operation = OPERATIONS[0]
        for i in range(len(self.expr) - 1):
            if exponent == MAX_EXPONENT + 1:
                exponent = 1
                operation_idx += 1
                if operation_idx == NUM_OPERATIONS:
                    break
                operation = OPERATIONS[operation_idx]
            coeff = self.expr[i]
            if coeff == 0:
                exponent += 1
                continue
            coeff_str = str(coeff if coeff != 1 else "")
            exponent_str = f'^{exponent}' if exponent != 1 else ""
            if operation == 'power':
                term = f'{coeff_str}{self.varstr}{exponent_str}'
            elif operation == 'sin':
                term = f'{coeff_str}sin{exponent_str}({self.varstr})'
            elif operation == 'cos':
                term = f'{coeff_str}cos{exponent_str}({self.varstr})'
            elif operation == 'ln':
                term = f'{coeff_str}ln{exponent_str}({self.varstr})'
            elif operation == 'e':
                term = f'{coeff_str}e^({exponent if exponent != 1 else ""}{self.varstr})'

            result.append(term)
            exponent += 1
        if self.expr[-1]:
            result.append(str(self.expr[-1]))
        return " + ".join(result)

In [ ]:
l1 = [3] * EXPR_LIST_SIZE
e1 = SimpleExpr(l1)
print(e1, end='\n\n')

l2 = [0] * EXPR_LIST_SIZE
l2[4] = 5
l2[16] = 73
l2[22] = 534
l2[50] = 200
e2 = SimpleExpr(l2)
print(e2, end='\n\n')

3x + 3x^2 + 3x^3 + 3x^4 + 3x^5 + 3x^6 + 3x^7 + 3x^8 + 3x^9 + 3x^10 + 3sin(x) + 3sin^2(x) + 3sin^3(x) + 3sin^4(x) + 3sin^5(x) + 3sin^6(x) + 3sin^7(x) + 3sin^8(x) + 3sin^9(x) + 3sin^10(x) + 3cos(x) + 3cos^2(x) + 3cos^3(x) + 3cos^4(x) + 3cos^5(x) + 3cos^6(x) + 3cos^7(x) + 3cos^8(x) + 3cos^9(x) + 3cos^10(x) + 3ln(x) + 3ln^2(x) + 3ln^3(x) + 3ln^4(x) + 3ln^5(x) + 3ln^6(x) + 3ln^7(x) + 3ln^8(x) + 3ln^9(x) + 3ln^10(x) + 3e^(x) + 3e^(2x) + 3e^(3x) + 3e^(4x) + 3e^(5x) + 3e^(6x) + 3e^(7x) + 3e^(8x) + 3e^(9x) + 3e^(10x) + 3

5x^5 + 73sin^7(x) + 534cos^3(x) + 200



In [ ]:
class Derivative():
    def __init__(self, expr, varstr='x'):
        if expr is not None:
            self.expr = expr.copy()
        else:
            self.expr = [0] * EXPR_LIST_SIZE
        self.varstr = varstr
    
    def __repr__(self):
        result = []
        exponent = 1
        operation_idx = 0
        operation = OPERATIONS[0]
        for i in range(len(self.expr) - 1):
            if exponent == MAX_EXPONENT + 1:
                exponent = 1
                operation_idx += 1
                if operation_idx == NUM_OPERATIONS:
                    break
                operation = OPERATIONS[operation_idx]
            coeff = self.expr[i]
            if coeff == 0:
                exponent += 1
                continue
            coeff_str = str(coeff if coeff != 1 else "")
            exponent_str = f'^{exponent}' if exponent != 1 else ""
            exponent_m1_str = f'^{exponent - 1}' if exponent - 1 != 1 else ""
            if operation == 'power':
                term = f'{coeff_str}{self.varstr}{exponent_str}'
            elif operation == 'sin':
                term = f'{coeff_str}{f"sin{exponent_m1_str}({self.varstr})" if exponent_str else ""}cos(x)'
            elif operation == 'cos':
                term = f'{coeff_str}{f"cos{exponent_m1_str}({self.varstr})" if exponent_str else ""}sin(x)'
            elif operation == 'ln':
                term = f'{coeff_str}{f"ln{exponent_m1_str}({self.varstr})" if exponent_str else ""}/x'
            elif operation == 'e':
                term = f'{coeff_str}e^({exponent if exponent != 1 else ""}{self.varstr})'

            result.append(term)
            exponent += 1
        if self.expr[-1]:
            result.append(str(self.expr[-1]))
        return " + ".join(result)

In [ ]:
l1 = [3] * EXPR_LIST_SIZE
e1 = Derivative(l1)
print(e1, end='\n\n')

l2 = [0] * EXPR_LIST_SIZE
l2[4] = 5
l2[16] = 73
l2[22] = 534
l2[50] = 200
e2 = Derivative(l2)
print(e2, end='\n\n')

3x + 3x^2 + 3x^3 + 3x^4 + 3x^5 + 3x^6 + 3x^7 + 3x^8 + 3x^9 + 3x^10 + 3cos(x) + 3sin(x)cos(x) + 3sin^2(x)cos(x) + 3sin^3(x)cos(x) + 3sin^4(x)cos(x) + 3sin^5(x)cos(x) + 3sin^6(x)cos(x) + 3sin^7(x)cos(x) + 3sin^8(x)cos(x) + 3sin^9(x)cos(x) + 3sin(x) + 3cos(x)sin(x) + 3cos^2(x)sin(x) + 3cos^3(x)sin(x) + 3cos^4(x)sin(x) + 3cos^5(x)sin(x) + 3cos^6(x)sin(x) + 3cos^7(x)sin(x) + 3cos^8(x)sin(x) + 3cos^9(x)sin(x) + 3/x + 3ln(x)/x + 3ln^2(x)/x + 3ln^3(x)/x + 3ln^4(x)/x + 3ln^5(x)/x + 3ln^6(x)/x + 3ln^7(x)/x + 3ln^8(x)/x + 3ln^9(x)/x + 3e^(x) + 3e^(2x) + 3e^(3x) + 3e^(4x) + 3e^(5x) + 3e^(6x) + 3e^(7x) + 3e^(8x) + 3e^(9x) + 3e^(10x) + 3

5x^5 + 73sin^6(x)cos(x) + 534cos^2(x)sin(x) + 200



In [ ]:

def derivative(expr):
    result = [0] * EXPR_LIST_SIZE
    for i in range(POWER_IDX, POWER_IDX + MAX_EXPONENT):
        if i == POWER_IDX:
            result[-1] += expr[i]
        else:
            exponent = i - POWER_IDX + 1
            result[i - 1] += exponent * expr[i]

    for i in range(SIN_IDX, SIN_IDX + MAX_EXPONENT):
        exponent = i - SIN_IDX + 1
        result[i] += exponent * expr[i]

    for i in range(COS_IDX, COS_IDX + MAX_EXPONENT):
        exponent = i - COS_IDX + 1
        result[i] -= exponent * expr[i]

    for i in range(LN_IDX, LN_IDX + MAX_EXPONENT):
        exponent = i - LN_IDX + 1
        result[i] += exponent * expr[i]

    for i in range(E_IDX, E_IDX + MAX_EXPONENT):
        exponent = i - E_IDX + 1
        result[i] += exponent * expr[i]
    return result

In [ ]:
l1 = list(range(4, 55))
print(SimpleExpr(l1))
print(Derivative(derivative(l1)))

4x + 5x^2 + 6x^3 + 7x^4 + 8x^5 + 9x^6 + 10x^7 + 11x^8 + 12x^9 + 13x^10 + 14sin(x) + 15sin^2(x) + 16sin^3(x) + 17sin^4(x) + 18sin^5(x) + 19sin^6(x) + 20sin^7(x) + 21sin^8(x) + 22sin^9(x) + 23sin^10(x) + 24cos(x) + 25cos^2(x) + 26cos^3(x) + 27cos^4(x) + 28cos^5(x) + 29cos^6(x) + 30cos^7(x) + 31cos^8(x) + 32cos^9(x) + 33cos^10(x) + 34ln(x) + 35ln^2(x) + 36ln^3(x) + 37ln^4(x) + 38ln^5(x) + 39ln^6(x) + 40ln^7(x) + 41ln^8(x) + 42ln^9(x) + 43ln^10(x) + 44e^(x) + 45e^(2x) + 46e^(3x) + 47e^(4x) + 48e^(5x) + 49e^(6x) + 50e^(7x) + 51e^(8x) + 52e^(9x) + 53e^(10x) + 54
10x + 18x^2 + 28x^3 + 40x^4 + 54x^5 + 70x^6 + 88x^7 + 108x^8 + 130x^9 + 14cos(x) + 30sin(x)cos(x) + 48sin^2(x)cos(x) + 68sin^3(x)cos(x) + 90sin^4(x)cos(x) + 114sin^5(x)cos(x) + 140sin^6(x)cos(x) + 168sin^7(x)cos(x) + 198sin^8(x)cos(x) + 230sin^9(x)cos(x) + -24sin(x) + -50cos(x)sin(x) + -78cos^2(x)sin(x) + -108cos^3(x)sin(x) + -140cos^4(x)sin(x) + -174cos^5(x)sin(x) + -210cos^6(x)sin(x) + -248cos^7(x)sin(x) + -288cos^8(x)sin(x) + -330

# Example random expressions

In [ ]:
import random

NUM_RANDOM_TERMS = 5
NUM_RANDOM_EXPRESSIONS = 10

for _ in range(NUM_RANDOM_EXPRESSIONS):
    expr = [0] * EXPR_LIST_SIZE
    for i in random.sample(range(EXPR_LIST_SIZE), NUM_RANDOM_TERMS):
        expr[i] = random.randint(-100, 100)
    print("Expression:", SimpleExpr(expr))
    print("Derivative:", Derivative(derivative(expr)), end='\n\n')

Expression: -61x^3 + 38cos^5(x) + 58cos^10(x) + -22ln^6(x) + -50ln^9(x)
Derivative: -183x^2 + -190cos^4(x)sin(x) + -580cos^9(x)sin(x) + -132ln^5(x)/x + -450ln^8(x)/x

Expression: 56sin^2(x) + 42sin^4(x) + 10sin^8(x) + -16ln^2(x) + -72e^(x)
Derivative: 112sin(x)cos(x) + 168sin^3(x)cos(x) + 80sin^7(x)cos(x) + -32ln(x)/x + -72e^(x)

Expression: -51x + -9x^3 + -56x^4 + 56sin^2(x) + -76sin^6(x)
Derivative: -27x^2 + -224x^3 + 112sin(x)cos(x) + -456sin^5(x)cos(x) + -51

Expression: 71x^2 + sin^2(x) + -4sin^7(x) + -40ln^7(x) + 10e^(2x)
Derivative: 142x + 2sin(x)cos(x) + -28sin^6(x)cos(x) + -280ln^6(x)/x + 20e^(2x)

Expression: 73x^5 + -50sin^5(x) + -65sin^10(x) + -80cos^9(x) + 95ln^2(x)
Derivative: 365x^4 + -250sin^4(x)cos(x) + -650sin^9(x)cos(x) + 720cos^8(x)sin(x) + 190ln(x)/x

Expression: 73sin(x) + 45cos^3(x) + 76ln^2(x) + 71ln^10(x) + -17e^(x)
Derivative: 73cos(x) + -135cos^2(x)sin(x) + 152ln(x)/x + 710ln^9(x)/x + -17e^(x)

Expression: 73x + -64x^9 + 53cos^5(x) + 73e^(4x) + -99e^(10x)
Der

In [ ]:
import numpy as np

for _ in range(NUM_RANDOM_EXPRESSIONS):
    expr = np.random.rand(EXPR_LIST_SIZE)
    print(expr)
    print("Expression:", SimpleExpr(expr))
    print("Derivative:", Derivative(derivative(expr)), end='\n\n')

[0.80953726 0.33630933 0.53030851 0.08704315 0.76980763 0.1636052
 0.52435972 0.63808337 0.84828799 0.59536826 0.35160498 0.59394446
 0.73310465 0.42517088 0.58060039 0.75333627 0.07617891 0.07037647
 0.82896195 0.01611417 0.43390108 0.68181845 0.78149921 0.79908595
 0.21471869 0.50868322 0.50225115 0.84536724 0.29889287 0.68798416
 0.14578581 0.34869094 0.97869122 0.84794902 0.22816833 0.67621312
 0.10756824 0.82817513 0.43768626 0.65252694 0.30437257 0.84570546
 0.3716826  0.66217483 0.90830145 0.39349846 0.57935873 0.81648527
 0.07303994 0.86637528 0.59503713]
Expression: 0.8095372563719357x + 0.3363093320747571x^2 + 0.5303085112748829x^3 + 0.08704314591372109x^4 + 0.7698076311464181x^5 + 0.1636052003599957x^6 + 0.5243597229152499x^7 + 0.6380833689238581x^8 + 0.8482879885967542x^9 + 0.5953682633319918x^10 + 0.3516049767227516sin(x) + 0.5939444563495989sin^2(x) + 0.733104654178463sin^3(x) + 0.42517087694165734sin^4(x) + 0.5806003863337534sin^5(x) + 0.7533362742724413sin^6(x) + 0.0761

# Neural Net

In [ ]:
X_train = []
y_train = []
for _ in range(1_000_000):
    y_train.append(np.random.randint(-5, 5, size=EXPR_LIST_SIZE))
    X_train.append(derivative(y_train[-1]))
    if (_ % 100_000 == 0):
        print(_, "iterations")
    

X_test = []
y_test = []
for _ in range(2000):
    y_test.append(np.random.randint(-5, 5, size=EXPR_LIST_SIZE))
    X_test.append(derivative(y_test[-1]))

X_train = np.array(X_train)
y_train = np.array(y_train)
X_test = np.array(X_test)
y_test = np.array(y_test)

print(X_train.shape)

0 iterations
100000 iterations
200000 iterations
300000 iterations
400000 iterations
500000 iterations
600000 iterations
700000 iterations
800000 iterations
900000 iterations
(1000000, 51)


In [ ]:
#Dependencies
import keras
from keras.models import Sequential
from keras.layers import Dense
# Neural network
model = Sequential()
model.add(Dense(EXPR_LIST_SIZE, input_dim=EXPR_LIST_SIZE, activation='relu'))
model.add(Dense(EXPR_LIST_SIZE, activation='relu'))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 51)                2652      
                                                                 
 dense_1 (Dense)             (None, 51)                2652      
                                                                 
Total params: 5,304
Trainable params: 5,304
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(loss='mean_squared_error', optimizer='adam', metrics=['accuracy'])

In [ ]:
history = model.fit(X_train, y_train, epochs=20, batch_size=100_000)


Epoch 1/20
10/10 [==============================] - 2s 179ms/step - loss: 81.0377 - accuracy: 0.0158
Epoch 2/20
10/10 [==============================] - 2s 183ms/step - loss: 45.8109 - accuracy: 0.0163
Epoch 3/20
10/10 [==============================] - 2s 179ms/step - loss: 27.9511 - accuracy: 0.0173
Epoch 4/20
10/10 [==============================] - 2s 179ms/step - loss: 19.1219 - accuracy: 0.0185
Epoch 5/20
10/10 [==============================] - 2s 178ms/step - loss: 14.6923 - accuracy: 0.0197
Epoch 6/20
10/10 [==============================] - 2s 180ms/step - loss: 12.3728 - accuracy: 0.0212
Epoch 7/20
10/10 [==============================] - 2s 178ms/step - loss: 11.0896 - accuracy: 0.0232
Epoch 8/20
10/10 [==============================] - 2s 179ms/step - loss: 10.3346 - accuracy: 0.0261
Epoch 9/20
10/10 [==============================] - 2s 180ms/step - loss: 9.8622 - accuracy: 0.0293
Epoch 10/20
10/10 [==============================] - 2s 181ms/step - loss: 9.5498 - accuracy

In [ ]:
model.evaluate(X_test, y_test)

print(X_test[:1])
print(model.predict(X_test[:1]))
print(y_test)

63/63 [==============================] - 0s 1ms/step - loss: 8.6906 - accuracy: 0.0600
[[ -2  12  -8  15  24 -14  16 -27  10   0  -1   4   0 -16  15   0 -14  24
    0  30   4  -2   9   8  15  24 -28 -32   0   0   3  -4   6 -20  10  -6
   14  24  36 -30   2   8   0 -20   0 -24   7 -32 -36  10   3]]
1/1 [==============================] - 0s 41ms/step
[[0.        0.        0.        0.        0.        0.        0.
  0.        0.        0.        0.        0.        0.        0.
  0.        0.        0.        0.        2.9412656 0.        0.
  0.        0.        0.        0.        0.        0.        0.
  0.        0.        0.        0.        0.        0.        0.
  0.        0.        4.539704  0.        0.        0.        0.
  0.        0.        0.        0.        0.        0.        0.
  0.        0.       ]]
[[ 3 -1  4 ... -4  1  1]
 [-2 -2  2 ...  3 -3 -5]
 [ 1 -2  1 ...  4 -3  4]
 ...
 [-1  4 -3 ...  0 -4 -2]
 [ 1  2  1 ...  3 -1 -4]
 [-4  3  2 ... -5  2  4]]
